services:
    # PHP service container
    ipa_app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ipa_app:1.0
        container_name: ipa_application
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        networks:
            - app_network

networks:
    app_network:
        driver: bridge